<footer class="footer">
  <div class="footer-inner">
    <div class="content-footer">
      <span class="title">Western Concepts Restaurant Group</span>
      <span class="address">(405) 605-2262  |  4318 N Western Avenue, OKlahoma city, OK 73118</span>
      <div id="block-wc-blocks-wc-blocks-brochure-block" class="block block-wc-blocks contextual-links-region">
        <div class="content">
          <a href="http://wc-portal.local/sites/default/files/wc_blocks_brochure_block/FunnelEyes_app.pdf" class="brochure-bnt link">Download our brochure</a>
        </div>
      </div>
    </div>
  </div>
</footer>