<div class="form-site-custom">
  <form action="#">
    <div class="form-wrapper-search">
      <div class="form-item">
        <input class="form-text" type="text" placeholder="Type here to start your search" />
      </div>
      <div class="btn-submit search-submit">
        <input class="form-submit btn" type="submit" value="SEARCH" />
      </div>
    </div>
    <div class="dropdown-settings">

    </div>
  </form>
  <div class="result-search">


  </div>
</div>

