<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="js/lib/modernizr.js"></script>
<script type="text/javascript" src="js/lib/jquery.min.js"></script>
<script type="text/javascript" src="js/lib/jquery.fancybox.pack.js"></script>

<script type="text/javascript" src="js/lib/jquery.mousewheel.js"></script>
<script type="text/javascript" src="js/lib/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="js/lib/jquery.superslides.js"></script>
<script type="text/javascript" src="js/lib/jquery.vislider.js"></script>
<script type="text/javascript" src="js/lib/jquery.viswitcher.js"></script>
<script type="text/javascript" src="js/lib/jquery.uniform.min.js"></script>
<script type="text/javascript" src="js/lib/combobox.js"></script>
<script type="text/javascript" src="js/lib/jquery.kwicks.js"></script>
<script type="text/javascript" src="js/lib/jquery.jscrollpane.min.js"></script>



<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="js/ie8lte.js"></script>
<![endif]-->

<script type="text/javascript" src="js/js.js"></script>




