<div class="b-bot-nav b-nav collapsed wrapper-drop-down">
  <div class="btn-dd">
    <a href="#">Home</a>
  </div>
  <div class="nav-items box-drop-down">
    <ul class="menu">
      <li>
        <a href="#">Home</a>
      </li>
      <li>
        <a href="#">About Us</a>
      </li>
      <li>
        <a href="#">Careers</a>
      </li>
      <li>
        <a href="#">Store</a>
      </li>
      <li>
        <a href="#">Calendar</a>
      </li>
      <li>
        <a href="#">Reward Card Members</a>
      </li>
      <li>
        <a href="#">Reservations</a>
      </li>
      <li>
        <a href="#">Progressive Dinner</a>
      </li>
    </ul>
  </div>
</div>