<div class="b-top-nav b-nav collapsed wrapper-drop-down">
  <a class="btn-dd" href="#"></a>
  <div class="nav-items box-drop-down">
    <h2><img src="theme/images/new-nav-icons/logo-wc.png" alt=""></h2>
    <ul class="menu">
      <li>
        <a href="#">
          <img src="theme/images/new-nav-icons/sushi-neko.png" alt="">
          <h3>Sushi Neko</h3>
        </a>
      </li>
      <li>
        <a href="#">
          <img src="theme/images/new-nav-icons/musashis.png" alt="">
          <h3>Musashi’s</h3>
        </a>
      </li>
      <li>
        <a href="#">
          <img src="theme/images/new-nav-icons/will-rogers-theatre.png" alt="">
          <h3>Will Rogers Theatre</h3>
        </a>
      </li>
      <li>
        <a href="#">
          <img src="theme/images/new-nav-icons/lobby-cafe-bar.png" alt="">
          <h3>Lobby Cafe & Bar</h3>
        </a>
      </li>
      <li>
        <a href="#">
          <img src="theme/images/new-nav-icons/tasting-room.png" alt="">
          <h3>The Tasting Room</h3>
        </a>
      </li>
      <li>
        <a href="#">
          <img src="theme/images/new-nav-icons/coach-house.png" alt="">
          <h3>The Coach House</h3>
        </a>
      </li>
    </ul>
  </div>
</div>