<meta charset="utf-8" />
<meta content="True" name="HandheldFriendly">
<meta content="320" name="MobileOptimized">
<meta content="telephone=no" name="format-detection">
<meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
<!--[if IE]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<![endif]-->
<link rel="shortcut icon" href="favicon.ico" type="image/vnd.microsoft.icon" />