<div class="outer-slides">
  <div class="slides-progressive">
    <div class="slides-container">
      <div class="slide-1 slide-progressive">
        <div class="content-slide">
          <div class="content-text">
            <div class="content">
              <div class="title-content">
                <h3>Progressive Dinner</h3>
              </div>
              <div class="text">
                <strong>Can’t decide which of our restaurants to try?</strong>
                <p>Then a <i>Western Concepts Progressive Dinner</i> package is perfect for you! Sample each of our
                  award-winning restaurants for a dining experience unlike anything else in Oklahoma City. It makes a
                  wonderful anniversary surprise, or just a fun night out on the town with friends. </p>
              </div>
            </div>
            <div class="images-decor">
              <img src="images/bg/bg_slide-sushi.png" alt="bg" class="preserve" />
            </div>
          </div>
        </div>
      </div>
      <div class="slide-2 slide-progressive">
        <div class="content-slide">
          <div class="content-slide-image">
            <div class="block-circle">
              <div class="number-slide">1</div>
              <div class="text-circle">
                <div class="text">
                  <p>
                   Dinner for <br>
                    <strong>2-6 people</strong>
                    <span>begins at either</span>
                    <strong> 6 pm or 7 pm</strong>
                    <span> with a sushi appetizer and sake at</span>
                    <strong>Sushi Neko</strong>
                  </p>
                </div>
              </div>
            </div>
            <div class="images-decor">
              <img src="images/bg/bg_slide_1.png" alt="bg" class="preserve" />
            </div>
          </div>
        </div>
      </div>
      <div class="slide-3 slide-progressive">
        <div class="content-slide">
          <div class="content-slide-image">
            <div class="block-circle">
              <div class="number-slide">2</div>
              <div class="text-circle">
                <div class="text">
                  <p>
                    <strong> Your entree course</strong>
                    <span>a steak dinner with red <br> wine, is a short walk to</span>
                    <strong>Musashi’s Japanese <br> STeakhouse</strong>
                  </p>
                </div>
              </div>
            </div>
            <div class="images-decor">
              <img src="images/bg/bg_slide_2.png" alt="bg" class="preserve" />
            </div>
          </div>
        </div>
      </div>
      <div class="slide-4 slide-progressive">
        <div class="content-slide">
          <div class="content-slide-image">
            <div class="block-circle">
              <div class="number-slide">3</div>
              <div class="text-circle">
                <div class="text">
                  <p>
                    <span>TOP OFF your <br> evening at </span>
                    <strong>The Lobby Café &amp; Bar</strong>
                    <span>with selected</span>
                    <strong>dessert &amp; cheeses</strong>
                    <span>paired with after-dinner</span>
                    <strong>cocktails or <br> champagne</strong>
                  </p>
                </div>
              </div>
            </div>
            <div class="images-decor">
              <img src="images/bg/bg_slide_3.png" alt="bg" class="preserve" />
            </div>
          </div>
        </div>
      </div>
      <div class="slide-5 slide-progressive">
        <div class="content-slide">
          <div class="block-circle">
            <div class="text-circle">
              <div class="text">
                <p>
                  <span>Your own</span>
                  <strong>personal concierge</strong>
                  <span>WILL coordinate the entire <br> night assuring that your meal <br> proceeds flawlessly.</span>
                  <span>ONCE YOU’VE SUBMITTED</span>
                  <strong>your reservation</strong>
                  <span>your personal concierge will <br> get in touch with you.</span>
                </p>
              </div>
            </div>
          </div>
          <div class="content-text content-form pull-right">
            <?php include 'src/com/blocks/forms/form-slide.inc'; ?>
          </div>
        </div>
      </div>
    </div>
    <nav class="slides-navigation">
      <a href="#" class="next">Next</a>
      <a href="#" class="prev">Previous</a>
    </nav>
  </div>
</div>