<div class="outer-slides-about-us slider-loading">
	<div class="slides-container">
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_1.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							1997
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>Carl Milam opens Sushi Neko</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_2.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							2001
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>Milam
									buys iconic Will Rogers Theatre building</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_3.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							2002
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>Will’s Coffee and Will Rogers Theatre Event Center open</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_4.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							2002
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>Musashi’s Japanese Steakhouse
									opens</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_5.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							2008
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>Kurt Fleischfresser
									becomes Food &amp; Beverage Director</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_6.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							2008
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>Will’s Coffee is renovated and converted to The Lobby Café &amp; Bar</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_7.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							2009
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>The Coach House merges with Western Concepts Restaurant Group</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slide">
			<div class="image">
				<img src="images/tmp/_img_slide_8.jpg" alt="" class="preserve">
				<div class="description">
					<div class="text-year">
						<div class="text">
							2011
						</div>
					</div>
					<div class="block-circle">
						<div class="text-circle">
							<div class="text">
								<p>The Tasting Room
									is completed</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>