<nav class="navigation navigation_header_top clearfix">
  <div class="wrapper-nav">
    <ul class="menu  ">
      <li class="active item-sushi_neko navigation-item">
        <a href="#" class="header-link">
          <span class="text-item">Sushi Neko</span>
        </a>
      </li>
      <li class="item-musashi navigation-item">
        <a href="#" class="header-link">
          <span class="text-item">Musashi’s</span>
        </a>
      </li>
      <li class="item-rogers_theatre navigation-item">
        <a href="#" class="header-link">
          <span class="text-item">Will Rogers Theatre</span>
        </a>
      </li>
      <li class="logo_top ">
        <a href="index.html" class="header-link">
          <span class="logo"><img src="images/nav_icon/logo_nav.png" alt="logo_nav" /></span>
        </a></li>
      <li class="item-lobby_cafe_bar navigation-item">
        <a href="#" class="header-link">
          <span class="text-item">Lobby Cafe &amp; Bar</span>
        </a>
      </li>
      <li class="item-tasting_room navigation-item">
        <a href="#" class="header-link">
          <span class="text-item">The Tasting Room</span>
        </a>
      </li>
      <li class="item-coach_house navigation-item">
        <a href="#" class="header-link">
          <span class="text-item">The Coach House</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

