<nav class="navigation navigation_header_bottom">
  <ul class="menu">
    <li class="active"><a href="#">Home</a></li>
    <li><a href="#">Chef’s Blog</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Careers </a></li>
    <li><a href="#">Store</a></li>
    <li><a href="#">Calendar</a></li>
    <li><a href="#">Rewards Card Members</a></li>
    <li><a href="#">Progressive Dinner</a></li>
    <li><a href="#">In the Community</a></li>
  </ul>
</nav>

