<div class="form-slide-wrapper">
  <div class="title-form">
    <h3>Make your reservation</h3>
  </div>
  <div class="form-site-custom">
    <form action="#">
      <fieldset class="form-fieldset">
        <div class="width-form-230">
          <div class="form-item">
            <label>Name of your party</label>
            <input type="text" class="form-text" />
          </div>
        </div>
        <div class="width-form-110">
          <div class="form-item">
            <label>Time</label>
            <select class="form-select">
              <option value="1">6:00 PM</option>
              <option value="2">6:00 PM</option>
              <option value="3">6:00 PM</option>
              <option value="4">6:00 PM</option>
              <option value="5">6:00 PM</option>
              <option value="6">6:00 PM</option>
              <option value="7">6:00 PM</option>
              <option value="8">6:00 PM</option>
              <option value="9">6:00 PM</option>
              <option value="10">6:00 PM</option>
            </select>
          </div>
        </div>

        <div class="width-form-110">
          <div class="form-item">
            <label>Date</label>
            <input type="text" class="form-text" />
          </div>
        </div>
        <div class="width-form-110 clear-left">
          <div class="form-item">
            <label>No. of guests </label>
            <select class="form-select">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
            </select>
          </div>
        </div>
        <div class="width-form-80 bg-dark-input">
          <div class="form-item">
            <label>Your total ($100 per guest)</label>
            <input class="form-text" type="text" />
          </div>
        </div>
        <div class="fieldset-description">
          <div class="form-item">
            <p>Because these dinners are so unique, we do require a minimum of two weeks advanced reservation.
              Availability of a Western Concepts Progressive Dinner is limited to Tuesday, Wednesday or Thursday
              evening.</p>
          </div>
        </div>
      </fieldset>
      <fieldset class="form-fieldset">
        <legend><span class="fieldset-legend">Personal Information</span></legend>
        <div class="width-form-170">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="First Name" />
          </div>
        </div>
        <div class="width-form-170">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="Last Name" />
          </div>
        </div>
        <div class="width-form-170">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="COMPANY" />
          </div>
        </div>
        <div class="width-form-534">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="ADDRESS" />
          </div>
        </div>
        <div class="width-form-261">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="CITY" />
          </div>
        </div>
        <div class="width-form-158">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="STATE" />
          </div>
        </div>
        <div class="width-form-91">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="ZIP" />
          </div>
        </div>
        <div class="width-form-261">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="HOME PHONE" />
          </div>
        </div>
        <div class="width-form-261">
          <div class="form-item">
            <input type="text" class="form-text" placeholder="email" />
          </div>
        </div>


      </fieldset>
      <fieldset class="form-fieldset">
        <legend><span class="fieldset-legend">Payment Information</span></legend>
        <div class="width-form-138 ff-tt-l">
          <div class="form-item">
            <label>SELECT CARD TYPE</label>
            <select class="form-select">
              <option value="1">MASTERCARD</option>
              <option value="2">MASTERCARD</option>
              <option value="3">MASTERCARD</option>
              <option value="4">MASTERCARD</option>
              <option value="5">MASTERCARD</option>
              <option value="6">MASTERCARD</option>
              <option value="7">MASTERCARD</option>
              <option value="8">MASTERCARD</option>
              <option value="9">MASTERCARD</option>
              <option value="10">MASTERCARD</option>
            </select>
          </div>
        </div>
        <div class="width-form-166 ff-tt-l">
          <div class="form-item">
            <label>EXPIRATION DATE</label>
            <input type="text" class="form-text" />
          </div>
        </div>
        <div class="width-form-100 not-label">
          <div class="form-item">
            <input class="form-text" type="text" placeholder="SECURITY CODE" />
          </div>
        </div>
        <div class="width-form-261 clear-left">
          <div class="form-item">
            <input class="form-text" type="text" placeholder="CARD NUMBER" />

          </div>
        </div>
        <div class="width-form-261">
          <div class="form-item">
            <input class="form-text" type="text" placeholder="NAME AS IT APPEARS ON CARD" />
          </div>
        </div>
      </fieldset>
      <div class="btn-wrapp">
        <div class="btn-submit">
          <input type="submit" value="SUBMIT" />
        </div>
      </div>
    </form>
  </div>
</div>


