<div class="form-fieldset-wrapper">
  <span class="legend-title">
    <span class="number-step">1</span>
    <span class="legend-span">Choose A Restaurant</span>
  </span>
  <figure class="images">
    <div class="image">
      <img src="images/tmp/_img_form_title.png" alt="img" />
    </div>
  </figure>
  <fieldset class="form-fieldset">
    <div class="form-item webform-component-radios">
      <div class="form-radios radio-group">
        <div class="form-item form-type-radio">
          <label for="id_radio_1">SUSHI NEKO</label>
          <input class="form-radio" type="radio" name="id_radio" id="id_radio_1" />
        </div>
        <div class="form-item form-type-radio">
          <label for="id_radio_2">WILL ROGERS THEATRE</label>
          <input class="form-radio" type="radio" name="id_radio" id="id_radio_2" />
        </div>
        <div class="form-item form-type-radio">
          <label for="id_radio_3">THE TASTING ROOM</label>
          <input class="form-radio" type="radio" name="id_radio" id="id_radio_3" />
        </div>
        <div class="form-item form-type-radio">
          <label for="id_radio_4">MUSASHI’S</label>
          <input class="form-radio" type="radio" name="id_radio" id="id_radio_4" />
        </div>
        <div class="form-item form-type-radio">
          <label for="id_radio_5">THE LOBBY CAFE &amp; BAR</label>
          <input class="form-radio" type="radio" name="id_radio" id="id_radio_5" />
        </div>
        <div class="form-item form-type-radio">
          <label for="id_radio_6">THE COACH HOUSE</label>
          <input class="form-radio" type="radio" name="id_radio" id="id_radio_6" />
        </div>


      </div>
    </div>
  </fieldset>
</div>