<div class="form-fieldset-wrapper">
  <span class="legend-title"><span class="number-step">7</span><span class="legend-span">Authorization</span></span>
  <fieldset class="form-fieldset form-wrapper">
    <div class="fieldset-wrapper">
      <div class="fieldset-description">
        <div class="form-item webform-component webform-component-markup">
          <p>I certify that the facts contained in this application are true and complete to the best of my
            knowledge and understand that, if employed, falsified statements on this application shall be
            grounds
            for dismissal.</p>

          <p>I authorize investigation of all statements contained herein and the references and employers
            listed
            above to give Aaction Rents any and all information concerning my previous employment and any
            pertinent information they may have, personal or otherwise, and relase the company from all
            liability
            for any damage that may result from utilization of such information.</p>

          <p>I also understand and agree that no representative of the company has the authority to enter into
            any
            agreement for employment for any specified period of time, or to make any agreement contrary to the
            foregoing, unless it is in writing and signed by an authorized Aaction Rents representative.</p>

          <p>This waiver does not permit the release or use of disability-related or medical information in a
            manner prohibited by the Americans with Disabilities Act (ADA) and other relevant federal and state
            laws.</p>

          <p>I understand that an offer of employment, and my continued employment are contingent upon
            satisfactory proof of my authorization to work in the United States.</p>
        </div>

      </div>
      <div class="width-form-194 clear-left">
        <div class="form-item form-type-date">
          <label>Date</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-296">
        <div class="form-item form-type-text">
          <label>Signed</label>
          <input class="form-text error" type="text" />
        </div>
      </div>
    </div>


  </fieldset>
</div>

<div class="btn-wrapp">
  <div class="btn-submit">
    <input type="submit" value="SUBMIT application">
  </div>
</div>