<div class="form-fieldset-wrapper">
  <span class="legend-title">
    <span class="number-step">6</span>
    <span class="legend-span">References</span>
  </span>
  <fieldset class="form-fieldset">
    <div class="fieldset-wrapper">
      <div class="legeng-bottom">
        <fieldset class="form-wrapper">
          <legend><span class="fieldset-legend">1</span></legend>
          <div class="fieldset-wrapper">
            <div class="width-form-194">
              <div class="form-item form-type-text">
                <label>Name </label>
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-296">
              <div class="form-item form-type-text ">
                <label>Address </label>
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-192">
              <div class="form-item form-type-text ">
                <label>Business</label>
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-158">
              <div class="form-item form-type-text ">
                <label>Phone</label>
                <input class="form-text" type="text" />
              </div>
            </div>
          </div>
        </fieldset>
      </div>
      <div class="legeng-bottom">
        <fieldset class="form-wrapper">
          <legend><span class="fieldset-legend">2</span></legend>
          <div class="fieldset-wrapper">
            <div class="width-form-194">
              <div class="form-item form-type-text">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-296">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-192">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-158">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
          </div>
        </fieldset>
      </div>
      <div class="legeng-bottom">
        <fieldset class="form-wrapper">
          <legend><span class="fieldset-legend">3</span></legend>
          <div class="fieldset-wrapper">
            <div class="width-form-194">
              <div class="form-item form-type-text">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-296">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-192">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-158">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
          </div>
        </fieldset>

      </div>
      <div class="legeng-bottom">
        <fieldset class="form-wrapper">
          <legend><span class="fieldset-legend">4</span></legend>
          <div class="fieldset-wrapper">
            <div class="width-form-194">
              <div class="form-item form-type-text">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-296">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-192">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
            <div class="width-form-158">
              <div class="form-item form-type-text ">
                <input class="form-text" type="text" />
              </div>
            </div>
          </div>
        </fieldset>

      </div>
    </div>
  </fieldset>
</div>