<div class="form-fieldset-wrapper">
  <span class="legend-title">
    <span class="number-step">3</span>
    <span class="legend-span">Employment Sought</span>
  </span>
  <fieldset class="form-fieldset">
    <div class="fieldset-wrapper">
      <div class=" ff-tt-l">
        <div class="form-item webform-component-radios">
          <label>Type of Employment</label>

          <div class="form-radios">
            <div class="form-item form-type-radio">
              <label>Full Time </label>
              <input type="radio" name="radio-radio" />
            </div>
            <div class="form-item form-type-radio">
              <label>Part Time </label>
              <input type="radio" name="radio-radio" />
            </div>
            <div class="form-item form-type-radio">
              <label>Temporary </label>
              <input type="radio" name="radio-radio" />
            </div>
            <div class="form-item form-type-radio">
              <label>Summer </label>
              <input type="radio" name="radio-radio" />
            </div>
            <div class="form-item form-type-radio">
              <label>Co-Op Education</label>
              <input type="radio" name="radio-radio" />
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="form-item form-type-select pull-right">
      <label>Choose a Position</label>
      <select class="form-select">
        <optgroup label="Item">
          <option value="1">Item 1</option>
          <option value="2">Item 2</option>
          <option value="3">Item 3</option>
          <option value="4">Item 4</option>
          <option value="5">Item 5</option>
        </optgroup>
        <optgroup label="Item">
          <option value="1">Item 1</option>
          <option value="2">Item 2</option>
          <option value="3">Item 3</option>
          <option value="4">Item 4</option>
          <option value="5">Item 5</option>
        </optgroup>
      </select>
    </div>
    <div class="ff-tt-l">
      <div class="form-item  webform-component-radios">
        <label>Times Available</label>

        <div class="form-radios">
          <div class="form-item form-type-radio">
            <label>Day Time</label>
            <input type="radio" name="radio-radio" />
          </div>
          <div class="form-item form-type-radio">
            <label>Evenings </label>
            <input type="radio" name="radio-radio" />
          </div>
          <div class="form-item form-type-radio">
            <label>Saturdays </label>
            <input type="radio" name="radio-radio" />
          </div>
          <div class="form-item form-type-radio">
            <label>Overtime</label>
            <input type="radio" name="radio-radio" />
          </div>
        </div>
      </div>
    </div>
    <div class="width-form-200">
      <div class="form-item form-type-text ">
        <label>Date you can start</label>
        <input type="text" class="form-text" />
      </div>
    </div>
    <div class="width-form-110">
      <div class="form-item form-type-text ">
        <label>Salary desired</label>
        <input type="text" class="form-text" />
      </div>
    </div>
    <div class="ff-tt-l clear-left">
      <div class="form-item  webform-component-radios">
        <label>Are you currently employed?</label>

        <div class="form-radios">
          <div class="form-item form-type-radio">
            <label>Yes </label>
            <input type="radio" name="radio-radio" />
          </div>
          <div class="form-item form-type-radio">
            <label>No </label>
            <input type="radio" name="radio-radio" />
          </div>
        </div>
      </div>
    </div>
    <div class="ff-tt-l">
      <div class="form-item  webform-component-radios">
        <label>If yes, may we contact your current employer?</label>

        <div class="form-radios">
          <div class="form-item form-type-radio">
            <label>Yes </label>
            <input type="radio" name="radio-radio" />
          </div>
          <div class="form-item form-type-radio">
            <label>No </label>
            <input type="radio" name="radio-radio" />
          </div>
        </div>
      </div>
    </div>
    <div class="width-form-110">
      <div class="form-item  form-type-text">
        <label>Please initial:</label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="ff-tt-l clear-left">
      <div class="form-item  webform-component-radios">
        <label>Have you ever applied with us before?</label>

        <div class="form-radios">
          <div class="form-item form-type-radio">
            <label>Yes </label>
            <input type="radio" name="radio-radio" />
          </div>
          <div class="form-item form-type-radio">
            <label>No </label>
            <input type="radio" name="radio-radio" />
          </div>
        </div>
      </div>
    </div>
    <div class="width-form-240">
      <div class="form-item  form-type-text">
        <label>If yes, where?</label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-240">
      <div class="form-item  form-type-text">
        <label>When?</label>
        <input class="form-text" type="text" />
      </div>
    </div>
  </fieldset>
</div>

