<div class="form-fieldset-wrapper">
  <span class="legend-title">
    <span class="number-step">2</span>
    <span class="legend-span">Personal Information</span>
  </span>
  <fieldset class="form-fieldset">
    <div class="width-form-310 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Last Name </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-310 ff-tt-l">
      <div class="form-item form-type-text">
        <label> First Name </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-240 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Social Security Number</label>
        <input class="form-text error" type="text" />
      </div>
    </div>
    <div class="width-form-310 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Current address</label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-310 ff-tt-l">
      <div class="form-item form-type-text">
        <label>City</label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-110 ff-tt-l">
      <div class="form-item form-type-text">
        <label>OK </label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-110 ff-tt-l">
      <div class="form-item form-type-text">
        <label>ZIP</label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-200 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Home Phone number </label>
        <input class="form-text error" type="text" />
      </div>
    </div>
    <div class="width-form-200 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Cell phone Number</label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-200 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Email address</label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-200 ff-tt-l  clear-left">
      <div class="form-item form-type-text">
        <label>Emergency Contact</label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-200 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Relation</label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-200 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Phone NUmber </label>
        <input class="form-text " type="text" />
      </div>
    </div>
    <div class="width-form-240 ff-tt-l">
      <div class="form-item form-type-text">
        <label>Referred by</label>
        <input class="form-text " type="text" />
      </div>
    </div>

  </fieldset>
</div>