<div class="form-fieldset-wrapper">
  <span class="legend-title">
    <span class="number-step">4</span>
    <span class="legend-span">Education</span>
  </span>
  <fieldset class="form-fieldset">
    <div class="width-form-350 ff-tt-l">
      <div class="form-item form-type-text">
        <label>GRAMMAR SCHOOL</label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-62 ff-tt-l">
      <div class="form-item form-type-text">
        <label>YEARS </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-146 ff-tt-l">
      <div class="form-item form-type-text">
        <label>GRADUATED </label>
        <input class="form-text" type="text" />
      </div>
    </div>

    <div class="width-form-282 ff-tt-l">
      <div class="form-item form-type-text">
        <label>SUBJECT(S) STUDIED</label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-350 ff-tt-l">
      <div class="form-item form-type-text">
        <label>HIGH SCHOOL </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-62 ff-tt-l">
      <div class="form-item form-type-text">
        <label>YEARS </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-146 ff-tt-l">
      <div class="form-item form-type-text">
        <label>GRADUATED </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-282 ff-tt-l">
      <div class="form-item form-type-text">
        <label>SUBJECT(S) STUDIED</label>
        <input class="form-text" type="text" />
      </div>
    </div>

    <div class="width-form-350 ff-tt-l">
      <div class="form-item form-type-text">
        <label>COLLEGE </label>
        <input class="form-text" type="text" />
      </div>
    </div>

    <div class="width-form-62 ff-tt-l">
      <div class="form-item form-type-text">
        <label>YEARS </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-146 ff-tt-l">
      <div class="form-item form-type-text">
        <label>GRADUATED </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-282 ff-tt-l">
      <div class="form-item form-type-text">
        <label>SUBJECT(S) STUDIED</label>
        <input class="form-text" type="text" />
      </div>
    </div>

    <div class="width-form-350 ff-tt-l">
      <div class="form-item form-type-text">
        <label>TRADE OR BUSINESS SCHOOL</label>
        <input class="form-text" type="text" />
      </div>
    </div>

    <div class="width-form-62 ff-tt-l">
      <div class="form-item form-type-text">
        <label>YEARS </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-146 ff-tt-l">
      <div class="form-item form-type-text">
        <label>GRADUATED </label>
        <input class="form-text" type="text" />
      </div>
    </div>
    <div class="width-form-282 ff-tt-l">
      <div class="form-item form-type-text">
        <label>SUBJECT(S) STUDIED</label>
        <input class="form-text" type="text" />
      </div>
    </div>

  </fieldset>
</div>


