<div class="form-fieldset-wrapper">
  <span class="legend-title">
    <span class="number-step">5</span>
    <span class="legend-span">Employment History</span>
  </span>
  <fieldset class="form-fieldset">
    <div class="fieldset-description">
      List your last four employers, starting with the most recent.
    </div>
    <fieldset class="form-wrapper">
      <legend>
        <span class="fieldset-legend">
          1
        </span>
      </legend>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>FROM</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>COMPANY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>PHONE</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l clear-left">
        <div class="form-item form-type-text">
          <label>TO</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ADDRESS </label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>CITY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>STATE</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ZIP</label>
          <input class="form-text" type="text" />
        </div>
      </div>


      <div class="width-form-200 clear-left">
        <div class="form-item form-type-text">
          <label>Salary </label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200">
        <div class="form-item form-type-text">
          <label>Position</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-460">
        <div class="form-item form-type-text">
          <label> Reason for leaving</label>
          <input class="form-text" type="text" />
        </div>
      </div>


    </fieldset>
    <fieldset class="form-wrapper">
      <legend>
        <span class="fieldset-legend">
          2
        </span>
      </legend>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>FROM</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>COMPANY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>PHONE</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l clear-left">
        <div class="form-item form-type-text">
          <label>TO</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ADDRESS </label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>CITY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>STATE</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ZIP</label>
          <input class="form-text" type="text" />
        </div>
      </div>


      <div class="width-form-200 clear-left">
        <div class="form-item form-type-text">
          <label>Salary </label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200">
        <div class="form-item form-type-text">
          <label>Position</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-460">
        <div class="form-item form-type-text">
          <label> Reason for leaving</label>
          <input class="form-text" type="text" />
        </div>
      </div>
    </fieldset>
    <fieldset class="form-wrapper">
      <legend>
        <span class="fieldset-legend">
          3
        </span>
      </legend>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>FROM</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>COMPANY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>PHONE</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l clear-left">
        <div class="form-item form-type-text">
          <label>TO</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ADDRESS </label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>CITY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>STATE</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ZIP</label>
          <input class="form-text" type="text" />
        </div>
      </div>


      <div class="width-form-200 clear-left">
        <div class="form-item form-type-text">
          <label>Salary </label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200">
        <div class="form-item form-type-text">
          <label>Position</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-460">
        <div class="form-item form-type-text">
          <label> Reason for leaving</label>
          <input class="form-text" type="text" />
        </div>
      </div>
    </fieldset>
    <fieldset class="form-wrapper">
      <legend>
        <span class="fieldset-legend">
          4
        </span>
      </legend>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>FROM</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>COMPANY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>PHONE</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200 ff-tt-l clear-left">
        <div class="form-item form-type-text">
          <label>TO</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ADDRESS </label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-200 ff-tt-l">
        <div class="form-item form-type-text">
          <label>CITY</label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>STATE</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-110 ff-tt-l">
        <div class="form-item form-type-text">
          <label>ZIP</label>
          <input class="form-text" type="text" />
        </div>
      </div>


      <div class="width-form-200 clear-left">
        <div class="form-item form-type-text">
          <label>Salary </label>
          <input class="form-text" type="text" />
        </div>
      </div>

      <div class="width-form-200">
        <div class="form-item form-type-text">
          <label>Position</label>
          <input class="form-text" type="text" />
        </div>
      </div>
      <div class="width-form-460">
        <div class="form-item form-type-text">
          <label> Reason for leaving</label>
          <input class="form-text" type="text" />
        </div>
      </div>
    </fieldset>
  </fieldset>
</div>


