<header id="header" class="header">
  <?php include "tpl/blocks/navs/top-nav.inc"; ?>
  <div class="header-inner">
    <div class="logo">
      <h1>Western concepts</h1>
      <img src="theme/images/logo.png" alt=""/>
    </div>
    <div class="card">
      <figure>
        <img src="theme/images/tmp/img-card.png" alt="">
        <figcaption>
          <a href="#">
            Learn about our
            <span>Gift Cards</span>
          </a>
        </figcaption>
      </figure>
    </div>
  </div>
  <?php include "tpl/blocks/navs/bot-nav.inc"; ?>
</header>